name: CICD
on:
  workflow_dispatch: 
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Code
        run: echo "Code clone from github"
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Code Tested Successfuly"

  Build:
     runs-on: ubuntu-latest
     steps:
      - name: Build
        run: echo "Code Build successfully"

  Deploy:
     runs-on: ubuntu-latest
     steps:
      - name: Deploy
        run: echo "Code Delpoy successfully"
      
