name: portfolio
on:
  push:
    branches: [main]
    
  workflow_dispatch: 
    
permissions: 
  pages: write
  contents: write
  id-token: write
jobs:
  Deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: configure pages
        uses: actions/configure-pages@v4

      - name: upload static files
        uses: actions/upload-pages-artifact@v4
        with:
          path: "."

      - name: deploy github pages
        uses: actions/deploy-pages@v4
      
          
